osx_image: xcode9
language: objective-c
sudo: required
env:
  global:
    - PROJECT="LoggerKit.xcodeproj"
    - SCHEME="LoggerKit-Package"
    - IOS_SDK="iphonesimulator11.0"
    - MACOS_SDK="macosx10.13"
    - TVOS_SDK="appletvsimulator11.0"
    - FRAMEWORK="LoggerKit"
    - CONFIGURATION="Debug"
    - CC_TEST_REPORTER_ID="fe0aa1e08edda399eadfff3386c2fc83fe3faba677d676a66e987649494d0a30"
  matrix:
    - SDK="$IOS_SDK"    DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.0"

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - swift --version

before_script:
  - set -o pipefail
  - pod repo update
  - swift package generate-xcodeproj
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - gem i slather

script:
  - xcodebuild clean build test
    -project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration "$CONFIGURATION"
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - brew install tree
  - tree /Users/ngtk/Library/Developer/Xcode/DerivedData/LoggerKit-*/
  - slather coverage --cobertura-xml --scheme $SCHEME --configuration $CONFIGURATION --output-directory ./ $PROJECT
  - pod lib lint

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
