osx_image: xcode9
language: objective-c
sudo: required
env:
  global:
    - PROJECT="LoggerKit.xcodeproj"
    - SCHEME="LoggerKit-Package"
    - IOS_SDK="iphonesimulator11.0"
    - MACOS_SDK="macosx10.13"
    - TVOS_SDK="appletvsimulator11.0"
    - FRAMEWORK="LoggerKit"
  matrix:
    - SDK="$IOS_SDK"      DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.0"

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - swift --version

before_script:
  - set -o pipefail
  - bundle exec pod repo update
  - swift package generate-xcodeproj

script:
  - xcodebuild clean build test
    -project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - bundle exec pod lib lint
